# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-08-03 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education_and_Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=b'pictures/', verbose_name=b'image')),
                ('title1', models.CharField(max_length=600)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=150)),
                ('bio', models.TextField()),
                ('twitter_url', models.URLField()),
                ('facebook_url', models.URLField()),
                ('linkedin_url', models.URLField()),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to=b'pictures/', verbose_name=b'image')),
                ('project_url', models.URLField(max_length=100)),
                ('github_url', models.URLField(max_length=500)),
            ],
        ),
    ]
